# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = 'sugarcrm'
  config.vm.box_url = 'http://files.vagrantup.com/precise64.box'

  config.vm.forward_port 80, 1080
  config.vm.forward_port 22, 2222
  config.vm.forward_port 3306, 13_306

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = 'cookbooks'
    chef.roles_path = 'roles'
    chef.add_role('sugarcrm')
  end
end
